class Aircraft {
  id: string;
  sidcPlatform: string;
  natoName?: string;

  constructor(id: string, sidcPlatform: string, natoName?: string) {
    this.id = id;
    this.sidcPlatform = sidcPlatform || "MFF-";
    this.natoName = natoName;
  }
}

class Plane extends Aircraft {
  constructor(id: string, sidcPlatform?: string, natoName?: string) {
    super(id, sidcPlatform || "MFF-", natoName);
  }
}

class Helicopter extends Aircraft {
  constructor(id: string, sidcPlatform?: string, natoName?: string) {
    super(id, sidcPlatform || "MHA-", natoName);
  }
}

export const planes: Record<string, Plane> = {
"A-10A": new Plane("A_10A", "MFA-"),
  "A-10C": new Plane("A_10C", "MFA-"),
  "A-10C_2": new Plane("A_10C_2", "MFA-"),
  "A-20G": new Plane("A_20G", "MFB-"),
  "A-50": new Plane("A_50", "MFRW"),
  "AH-1W": new Helicopter("AH_1W"),
  "AH-64A": new Helicopter("AH_64A"),
  "AH-64D": new Helicopter("AH_64D"),
  "AJS37": new Plane("AJS37"),
  "AV8BNA": new Plane("AV8BNA", "MFL-"),
  "An-26B": new Plane("An_26B", "MFC-"),
  "An-30M": new Plane("An_30M", "MFU-"),
  "B-17G": new Plane("B_17G", "MFB-"),
  "B-1B": new Plane("B_1B", "MFB-"),
  "B-52H": new Plane("B_52H", "MFB-"),
  "Bf-109K-4": new Plane("Bf_109K_4"),
  "C-101CC": new Plane("C_101CC"),
  "C-101EB": new Plane("C_101EB", "MFT-"),
  "C-130": new Plane("C_130", "MFC-"),
  "C-17A": new Plane("C_17A", "MFC-"),
  "CH-47D": new Helicopter("CH_47D", "MHC-"),
  "CH-53E": new Helicopter("CH_53E", "MHC-"),
  "Christen Eagle II": new Plane("Christen_Eagle_II"),
  "E-2C": new Plane("E_2C", "MFRW"),
  "E-3A": new Plane("E_3A", "MFRW"),
  "F-117A": new Plane("F_117A", "MFA-"),
  "F-14A": new Plane("F_14A"),
  "F-14A-135-GR": new Plane("F_14A_135_GR"),
  "F-14B": new Plane("F_14B"),
  "F-15C": new Plane("F_15C"),
  "F-15E": new Plane("F_15E"),
  "F-16A MLU": new Plane("F_16A_MLU"),
  "F-16A": new Plane("F_16A"),
  "F-16C bl.50": new Plane("F_16C_bl_50"),
  "F-16C bl.52d": new Plane("F_16C_bl_52d"),
  "F-16C_50": new Plane("F_16C_50"),
  "F-4E": new Plane("F_4E"),
  "F-4E-45MC":  new Plane("F_4E_45MC"),
  "F-5E": new Plane("F_5E"),
  "F-5E-3": new Plane("F_5E_3"),
  "F-86F Sabre": new Plane("F_86F_Sabre"),
  "F/A-18A": new Plane("F_A_18A"),
  "F/A-18C": new Plane("F_A_18C"),
  "FA-18C_hornet": new Plane("FA_18C_hornet"),
  "FW-190A8": new Plane("FW_190A8"),
  "FW-190D9": new Plane("FW_190D9"),
  "Hawk": new Plane("Hawk"),
  "I-16": new Plane("I_16"),
  "IL-76MD": new Plane("IL_76MD", "MFKD"),
  "IL-78M": new Plane("IL_78M", "MFKD"),
  "J-11A": new Plane("J_11A", undefined, "Flanker"),
  "JF-17": new Plane("JF_17"),
  "Ju-88A4": new Plane("Ju_88A4"),
  "KC-135": new Plane("KC_135", "MFC-"),
  "KC130": new Plane("KC130", "MFKD"),
  "KC135MPRS": new Plane("KC135MPRS", "MFKD"),
  "KJ-2000": new Plane("KJ_2000", "MFRW"),
  "Ka-27": new Helicopter("Ka_27"),
  "Ka-50": new Helicopter("Ka_50"),
  "L-39C": new Plane("L_39C"),
  "L-39ZA": new Plane("L_39ZA"),
  "M-2000C": new Plane("M_2000C"),
  "MQ-9 Reaper": new Plane("MQ_9_Reaper", "MFQD"),
  "Mi-24P": new Helicopter("Mi_24P"),
  "Mi-24V": new Helicopter("Mi_24V"),
  "Mi-26": new Helicopter("Mi_26"),
  "Mi-28N": new Helicopter("Mi_28N"),
  "Mi-8MT": new Helicopter("Mi_8MT"),
  "MiG-15bis": new Plane("MiG_15bis"),
  "MiG-19P": new Plane("MiG_19P", undefined, "Farmer"),
  "MiG-21Bis": new Plane("MiG_21Bis", undefined, "Fishbed"),
  "MiG-23MLD": new Plane("MiG_23MLD", undefined, "Flogger"),
  "MiG-25PD": new Plane("MiG_25PD", undefined, "Foxbat"),
  "MiG-25RBT": new Plane("MiG_25RBT", undefined, "Foxbat"),
  "MiG-27K": new Plane("MiG_27K", undefined, "Flanker"),
  "MiG-29A": new Plane("MiG_29A", undefined, "Fulcrum"),
  "MiG-29G": new Plane("MiG_29G", undefined, "Fulcrum"),
  "MiG-29S": new Plane("MiG_29S", undefined, "Fulcrum"),
  "MiG-31": new Plane("MiG_31", undefined, "Foxhound"),
  "Mirage 2000-5": new Plane("Mirage_2000_5"),
  "OH-58D": new Helicopter("OH_58D"),
  "P-47D-30": new Plane("P_47D_30"),
  "P-47D-30bl1": new Plane("P_47D_30bl1"),
  "P-47D-40": new Plane("P_47D_40"),
  "P-51D": new Plane("P_51D"),
  "P-51D-30-NA": new Plane("P_51D_30_NA"),
  "RQ-1A Predator": new Plane("RQ_1A_Predator", "MFQA"),
  "S-3B Tanker": new Plane("S_3B_Tanker", "MFKD"),
  "S-3B": new Plane("S_3B", "MFPN"),
  "SA342L": new Helicopter("SA342L"),
  "SA342M": new Helicopter("SA342M"),
  "SA342Minigun": new Helicopter("SA342Minigun"),
  "SA342Mistral": new Helicopter("SA342Mistral"),
  "SH-3W": new Helicopter("SH_3W"),
  "SH-60B": new Helicopter("SH_60B"),
  "SpitfireLFMkIX": new Plane("SpitfireLFMkIX"),
  "SpitfireLFMkIXCW": new Plane("SpitfireLFMkIXCW"),
  "Su-17M4": new Plane("Su_17M4", undefined, "Fitter"),
  "Su-24M": new Plane("Su_24M", undefined, "Fencer"),
  "Su-24MR": new Plane("Su_24MR", undefined, "Fencer"),
  "Su-25": new Plane("Su_25", "MFA-"),
  "Su-25T": new Plane("Su_25T", "MFA-"),
  "Su-25TM": new Plane("Su_25TM", "MFA-"),
  "Su-27": new Plane("Su_27", undefined, "Flanker"),
  "Su-30": new Plane("Su_30", undefined, "Flanker"),
  "Su-33": new Plane("Su_33", undefined, "Flanker"),
  "Su-34": new Plane("Su_34", undefined, "Fullback"),
  "TF-51D": new Plane("TF_51D"),
  "Tornado GR4": new Plane("Tornado_GR4"),
  "Tornado IDS": new Plane("Tornado_IDS"),
  "Tu-142": new Plane("Tu_142", "MFR-"),
  "Tu-160": new Plane("Tu_160", "MFB-"),
  "Tu-22M3": new Plane("Tu_22M3", "MFB-"),
  "Tu-95MS": new Plane("Tu_95MS", "MFB-"),
  "UH-1H": new Helicopter("UH_1H"),
  "UH-60A": new Helicopter("UH_60A", "MHU-"),
  "WingLoong-I": new Plane("WingLoong_I"),
  "Yak-40": new Plane("Yak_40"),
  "Yak-52": new Plane("Yak_52"),
};
